spring:
  application:
    name: api-gateway
server:
  servlet:
    context-path: api
  port: 10011

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eureka-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
