spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/coldestleon/spring-cloud-config-in-action
          search-paths: config-repo
          username: 562250082@qq.com
          password: xue599204267
        overrides:
          from: override-from
  datasource:
    username: xueyp
    password: {cipher}xue599204267

server:
  port: 10008

security:
  user:
    name: user
    password: xue599204267
